#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016

shopt -s extglob globstar nullglob

# model export #

black= red= green= yellow= blue= magenta= cyan= white= reset=

if [[ -t 1 ]]
then
	black=$(tput setaf 0)
	red=$(tput setaf 1)
	green=$(tput setaf 2)
	yellow=$(tput setaf 3)
	blue=$(tput setaf 4)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	reset=$(tput sgr0)
fi

version="20-08-2016"
script=$(basename -- "$0")

while (($#))
do
	case "$1" in
		-l|--ldr)
			extension_filter="ldr"
			;;
		-m|--mpd)
			extension_filter="mpd"
			;;
		-3ds)
			option="3ds"
			;;
		-b|--blender)
			option="blender"
			;;
		-wf|--wavefront)
			option="wavefront"
			;;
		-h|--help)
			echo -e "Usage:"
			echo -e "./$script [EXTENSION] [OPTION]"
			echo -e ""
			echo -e "Utility options:"
			echo -e "-l, --ldr \t\t Selects ldr file format as target."
			echo -e "-m, --mpd \t\t Selects mpd file format as target."
			echo -e "-3ds \t\t\t Export 3ds file format only."
			echo -e "-b, --blender \t\t\t Export blender file format only."
			echo -e "-wf, --wavefront \t Export wavefront (obj and mtl as zip archive) file format only."
			echo -e "-h, --help \t\t Show help options."
			echo -e "-v, --version \t Print version."
			exit
			;;
		-v|--version)
			echo -e "$script $version"
			exit
			;;
		*)
			echo -e "$script: Unknown option $1"
			echo -e "Try '$script --help' for options information."
			exit
			;;
		esac
	shift
done

# Test for utility dependencies and requirements

for binary_name in \
"leocad" \
"blender" \
"zip"
do
	binary=$(which $binary_name)

	if [[ -z "$binary" ]] # If binary is not found or unspecified
	then
		echo "${yellow}The '$binary_name' binary does not seem to be installed or present on your system.${reset}"
		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"

		read reply

		if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
		then
			# Specify binary location or exit on 'Cancel'

			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || exit

			binary="$binary_path/$binary"
		else
			echo "${red}Could not specify '$binary_name' binary installed on system.${reset}"
			echo "${red}Please install '$binary_name' using your system's package manager${reset}"
			echo "${red}and restart this utility when you are done.${reset}"
			echo ""
			exit 1
		fi

	elif [[ ! -z "$binary" ]] # If binary exists
	then
		echo "${green}'$binary' binary found on system - Continuing...${reset}"
		echo ""
	fi

	sleep 1
done

if [[ "$extension_filter" == "ldr" ]]
then
	extension_filter="ldr"
	extension="ldr"

elif [[ "$extension_filter" == "mpd" ]]
then
	extension_filter="mpd"
	extension="mpd"
else
	extension_filter="mpd"
	extension="mpd"

	echo "${yellow}Defaulting to $extension file format option.${reset}" # Warning when no option set for file type
	echo""
fi

if [[ "$option" == "3ds" ]]
then
	export_option="-3ds"
	export_extension="3ds"

elif [[ "$option" == "blender" ]]
then
	export_option="-3ds"
	export_extension="blend"

elif [[ "$option" == "wavefront" ]]
then
	export_option="-wf"
	export_extension="obj"
else
	option="blender"
	export_option="-3ds"
	export_extension="blend"

	echo "${yellow}Defaulting to $export_extension file export option.${reset}" # Warning when no option set for export type
	echo ""
fi

# Generate temporary content

beautify=$(mktemp /tmp/beautify.XXXXXX)
trap 'rm -rf "$beautify"' EXIT

# Push python blender beautifier conversion script to temporary file

cat > "$beautify" << 'PYTHON'
#!/usr/bin/env python3

import os
import bpy
from sys import argv

context = bpy.context

# arguments #
# [blender, --background, --python, script, 3ds]
# model_path = argv[4]

# prepare scene #

for obj in context.scene.objects:
	obj.select = True

bpy.ops.object.delete()

# import #

export_model = argv[4]
bpy.ops.import_scene.autodesk_3ds(filepath=export_model)

# join objects #

context.scene.objects.active = context.selected_objects[0]
bpy.ops.object.join()

# normalize transforms #
bpy.ops.object.transform_apply(
	location = True,
	rotation = True,
	scale = True
)

# add smooth shade and edge split modifiers #

bpy.ops.object.shade_smooth()
bpy.ops.object.modifier_add(
	type = "EDGE_SPLIT"
)

# remove doubles #

bpy.ops.object.editmode_toggle()
bpy.ops.mesh.remove_doubles()
bpy.ops.mesh.normals_make_consistent(
	inside = False
)
bpy.ops.object.editmode_toggle()

# save #

blend_file = export_model.replace(".3ds",".blend")
bpy.ops.wm.save_as_mainfile(
	filepath = blend_file,
	compress = True
)

# print output #

print("saved as:", blend_file)
bpy.ops.wm.quit_blender()
PYTHON

# Confirm options being used before processing

echo "${cyan}Utility started using the $extension file format option.${reset}"
echo "${cyan}Utility started using the $option file format option.${reset}"
echo ""

echo "${cyan}Please specify the directory in which you would like the ldraw model files to the be exported to the specified format.${reset}"

# Specify directory location or exit on 'Cancel'

directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || exit

IFS=$'\n'
selection=($directory)

for directory in "${selection[@]}"
do
	cd "$directory" || exit

	for model in "${directory%/}"/**/*."$extension_filter"
	do
		IFS='/'
		read -r -a path <<< "$directory"

		media_directory=${path[1]}
		disk_directory=${path[2]}
		dropbox_directory=${path[3]}
		lego_directory=${path[4]}
		models_directory=${path[5]}
		model_type_directory=${path[6]}
		model_directory=${path[7]}

		# Define directory and file variables

		exports_directory="/media/Disk/Dropbox/Lego/exports"
		uid_list="/media/Disk/Dropbox/Linux/scripts/ldraw/sketchfab/uid-list"

		model_export="${model##*/}"
		model_export_name="${model_export%.*}"
		model_export_name_clean="${model_export_name:5}"

		current_directory="$exports_directory/$model_type_directory/$model_export_name_clean/"
		current_file="$exports_directory/$model_type_directory/$model_export_name_clean/$model_export_name_clean.$export_extension"

		# Explicit file types

		current_file_3ds="$exports_directory/$model_type_directory/$model_export_name_clean/$model_export_name_clean.3ds"
		current_file_blend="$exports_directory/$model_type_directory/$model_export_name_clean/$model_export_name_clean.blend"

		# Check for the exports directory existence

		if [ ! -d "$exports_directory/$model_type_directory/$model_export_name_clean" ]
		then
			mkdir -p "$exports_directory/$model_type_directory/$model_export_name_clean"
		fi

		# Export 3DS file

		if [[ "$option" = "3ds" ]]
		then
			echo "${cyan}Exporting $model ("$export_extension")...${reset}"

			"$leocad" "$model" "$export_option" "$current_file" >> /dev/null

			wait
		fi

		# Export optimized blend file

		if [[ "$option" = "blender" ]]
		then
			echo "${cyan}Exporting $model ("$export_extension")...${reset}"

			# Generate 3DS file

			"$leocad" "$model" "$export_option" "$current_file" >> /dev/null

			echo "${cyan}Converting $model ("$export_extension")...${reset}"

			# Import 3DS file into blender to create optimized blend file

			"$blender" --background --python "$beautify" "$current_file_3ds" >> /dev/null

			# Cleanup

			rm -rf "$current_file_3ds"

			wait
		fi

		# Export wavefront file with materials archive

		if [[ "$option" = "wavefront" ]] && [[ -e *.obj ]] && [[ -e *.mtl ]]
		then
			cd "$exports_directory/$model_path" || exit

			# Archive .obj and respective .mtl files for exported model
			# when using the wavefront file export option for easy model upload or update

			zip "${model_export_name}.zip" {*.obj,*.mtl}
			rm -rf {*.obj,*.mtl}

			wait
		fi

		echo ""

		# Compare model name to uid list model entry and generate uid token file
		# under model's export directory for proper update authentication

		# Read UID from list

		while IFS=$'\t'
		read -r model_uid model_name
		do
			if [[ "$model_name" == "$model_export_name_clean" ]] # If model export name matches list entry
			then
				model_list_uid_message="${green}Model export name matches UID list entry...${reset}"
				list_uid="$model_uid"
				color=$(tput setaf 2) # green

				echo "$model_uid" > "$current_directory/uid"
			else
				: # pass

				model_list_uid_message="${red}Model export name does not match UID list entry...${reset}"
				list_uid="N/A"
				color=$(tput setaf 1) # red
			fi

		done < "$uid_list"

		# Read UID from file

		if [[ -e "$current_directory/uid" ]]
		then
			model_read_uid_message="${green}UID file exists under model export directory...${reset}"
			read_uid=$(cat "$current_directory"/uid)

			if [[ -z "$read_uid" ]]
			then
				model_read_uid_message="${red}UID file empty or not found...${reset}"
				read_uid="N/A"
			fi
		fi

		# Verify exported file size and display message accordingly (Free account model upload limit: 50MB)

		model_size=$(ls -s --block-size=MB "$current_file_blend" | awk '{print $1}')

		model_size_threshold="50"
		model_size_number="${model_size%MB}"

		if [[ "$model_size_number" -le "$model_size_threshold" ]]
		then
			model_size_message="${green}Model file size is below ${model_size_threshold}MB [ $model_size ] - File size threshold not exceeded.${reset}"
			color=$(tput setaf 2) # green

		elif [[ "$model_size_number" -gt "$model_size_threshold" ]]
		then
			model_size_message="${red}Warning: Model file size is above ${model_size_threshold}MB [ $model_size ] - Model cannot be uploaded to free subscription account due to maximum size limitation.${reset}"
			color=$(tput setaf 1) # red
		fi

		echo "${message}"
		echo "${confirmation}"
		echo ""
		echo "${model_list_uid_message}"
		echo "Model ID (List)...: $list_uid"
		echo "${model_read_uid_message}"
		echo "Model ID (File)...: $read_uid"
		echo ""
		echo "Model name........: $model_export_name_clean"
		echo "Model size........: $model_size"
		echo ""
		echo "${model_size_message}"
		echo ""

		echo "${cyan}Done.${reset}"
		echo ""
	done
done
