#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016

shopt -s extglob globstar nullglob

# model export #

black= red= green= yellow= blue= magenta= cyan= white= reset=

if [[ -t 1 ]]
then
	black=$(tput setaf 0)
	red=$(tput setaf 1)
	green=$(tput setaf 2)
	yellow=$(tput setaf 3)
	blue=$(tput setaf 4)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	reset=$(tput sgr0)
fi

version="03-06-2016"
script=$(basename -- "$0")

while (($#))
do
	case "$1" in
		-l|--ldr)
			extension_filter="ldr"
			;;
		-m|--mpd)
			extension_filter="mpd"
			;;
		-3ds)
			option="3ds"
			;;
		-wf|--wavefront)
			option="wavefront"
			;;
		-h|--help)
			echo -e "Usage:"
			echo -e "./$script [EXTENSION] [OPTION]"
			echo -e ""
			echo -e "Utility options:"
			echo -e "-l, --ldr \t\t Selects ldr file format as target."
			echo -e "-m, --mpd \t\t Selects mpd file format as target."
			echo -e "-3ds \t\t\t Export 3ds file format only."
			echo -e "-wf, --wavefront \t Export wavefront (obj and mtl as zip archive) file format only."
			echo -e "-h, --help \t\t Show help options."
			echo -e "-v, --version \t Print version."
			exit
			;;
		-v|--version)
			echo -e "$script $version"
			exit
			;;
		*)
			echo -e "$script: Unknown option $1"
			echo -e "Try '$script --help' for options information."
			exit
			;;
		esac
	shift
done

# Test for utility dependencies and requirements

for binary in \
"leocad" \
"blender" \
"zip"
do
	binary=$(which $binary)

	if [[ -z "$binary" ]] # If binary is not found or unspecified
	then
		echo "${yellow}The '$binary' binary does not seem to be installed or present on your system.${reset}"
		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"

		read reply

		if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
		then
			# Specify binary location or exit on 'Cancel'

			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit

			binary="$bnary_path/$binary"
		else
			echo "${red}Could not specify '$binary' binary installed on system.${reset}"
			echo "${red}Please install '$binary' using your system's package manager${reset}"
			echo "${red}and restart this utility when you are done.${reset}"
			echo ""
			exit 1
		fi

	elif [[ ! -z "$binary" ]] # If binary exists
	then
		echo "${green}'$binary' binary found on system - Continuing...${reset}"
		echo ""
	fi

	sleep 1
done

if [[ "$extension_filter" == "ldr" ]]
then
	extension_filter="ldr"
	extension="ldr"

elif [[ "$extension_filter" == "mpd" ]]
then
	extension_filter="mpd"
	extension="mpd"
else
	extension_filter="mpd"
	extension="mpd"

	echo "${yellow}Defaulting to mpd file format option.${reset}"
	echo""
fi

if [[ "$option" == "3ds" ]]
then
	export_option="-3ds"
	export_extension="3ds"

elif [[ "$option" == "wavefront" ]]
then
	export_option="-wf"
	export_extension="obj"
else
	export_option="-3ds"
	export_extension="3ds"

	echo "${yellow}Defaulting to 3ds file format option.${reset}" # Warning when no option set for file type
	echo ""
fi

# Generate temporary directory

beautify=$(mktemp /tmp/beautify.XXXXXX)
trap 'rm -rf "$beautify"' EXIT

# Push python blender beautifier conversion script to temporary file

cat > "$beautify" << 'PYTHON'
#!/usr/bin/env python3

import os
import bpy
context = bpy.context

# prepare scene #

for obj in context.scene.objects:
	obj.select = True

bpy.ops.object.delete()

# read file path from file #

with open("/tmp/model_file", "r") as file:
	export_model = file.read().rstrip()

# import #

bpy.ops.import_scene.autodesk_3ds(filepath=export_model)

# join objects #

context.scene.objects.active = context.selected_objects[0]
bpy.ops.object.join()

# normalize transforms #
bpy.ops.object.transform_apply(
	location = True,
	rotation = True,
	scale = True
)

# add smooth shade and edge split modifiers #

bpy.ops.object.shade_smooth()
bpy.ops.object.modifier_add(
	type = "EDGE_SPLIT"
)

# remove doubles #

bpy.ops.object.editmode_toggle()
bpy.ops.mesh.remove_doubles()
bpy.ops.mesh.normals_make_consistent(
	inside = False
)
bpy.ops.object.editmode_toggle()

# save #

blend_file = export_model.replace(".3ds",".blend")
bpy.ops.wm.save_as_mainfile(
	filepath = blend_file,
	compress = True
)

# print output #

print("saved as:", blend_file)
PYTHON

# Confirm options being used before processing

echo "${cyan}Utility started using the $extension file format option.${reset}"
echo "${cyan}Utility started using the $option file format option.${reset}"
echo ""

echo "${cyan}Please specify the directory in which you would like the ldraw model files to the be exported to the specified format.${reset}"

# Specify directory location or exit on 'Cancel'

directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit

IFS=$'\n'
selection=($directory)

for directory in "${selection[@]}"
do
	cd "$directory" || exit

	for model in "${directory%/}"/**/*."$extension_filter"
	do
		IFS='/'
		read -r -a path <<< "$directory"

		media_directory=${path[1]}
		disk_directory=${path[2]}
		dropbox_directory=${path[3]}
		lego_directory=${path[4]}
		models_directory=${path[5]}
		model_type_directory=${path[6]}
		model_directory=${path[7]}

		# Define directory and file variables

		exports_directory="/media/Disk/Dropbox/Lego/exports"
		uid_list="/media/Disk/Dropbox/Linux/scripts/ldraw/sketchfab/uid-list"

		model_file_log=$(mktemp /tmp/model_file)
		trap 'rm -rf "$model_file_log"' EXIT

		model_export="${model##*/}"
		model_export_name="${model_export%.*}"
		model_export_name_clean="${model_export_name:5}"

		current_directory="$exports_directory/$model_type_directory/$model_export_name_clean/"
		current_file="$exports_directory/$model_type_directory/$model_export_name_clean/$model_export_name_clean.$export_extension"

		# Explicit file types

		current_file_3ds="$exports_directory/$model_type_directory/$model_export_name_clean/$model_export_name_clean.3ds"
		current_file_blend="$exports_directory/$model_type_directory/$model_export_name_clean/$model_export_name_clean.blend"

		# Check for the exports directory existence

		if [ ! -d "$exports_directory/$model_type_directory/$model_export_name_clean" ]
		then
			mkdir -p "$exports_directory/$model_type_directory/$model_export_name_clean"
		fi

		echo "${cyan}Exporting $model ("$export_extension")...${reset}"

		"$leocad" "$model" "$export_option" "$current_file" &> /dev/null

		# Append current file to temporary log for confirmation

		echo "$current_file" > "$model_file_log"

		# Run blender beautifier to smooth surfaces and recalculate normals

		echo "${cyan}Converting $model (blender)...${reset}"

		blender --background --python "$beautify" >> /dev/null

		wait

		echo ""

		# Archive .obj and respective .mtl files for exported model when using the wavefront file export option for easy model upload or update

		if [[ mode="wavefront" ]] && [[ -e *.obj ]] && [[ -e *.mtl ]]
		then
			cd "$exports_directory/$model_path" || exit

			zip "${model_export_name}.zip" {*.obj,*.mtl}
			rm -rf {*.obj,*.mtl}
		fi

		# Compare model name to uid list model entry and generate uid token file under model's export directory for proper update authentication

		while IFS=$'\t'
		read -r uid model_name
		do
			if [[ "$model_name" == "$model_export_name_clean" ]] # If model export name matches list entry
			then
				if [[ -s "$current_directory"/uid ]]
				then
					read_uid=$(cat "$current_directory"/uid)
				fi

				echo "${green}Model export name matches UID list entry - Generating UID token...${reset}"

				if [[ ! -e "$current_directory/uid" ]] # If UID file does not exist in export model directory
				then
					message="${red}No UID file detected for $model_name - Generating UID token...${reset}"
					confirmation="${green}Found match..: [ $model_name - $model_export_name_clean ]${reset}"

				elif [[ ! -s "$current_directory/uid" ]] # If UID file exists in export model directory but is empty
				then
					uid="$read_uid"
					message="${yellow}UID file already exists [ empty ] - Writing UID token...${reset}"
					confirmation="${yellow}Write confirmation:${reset} Model ID from file: $uid" # Confirm write

				elif [[ -s "$current_directory/uid" ]] # If UID file exists in export model directory
				then
					uid="$read_uid"
					message="${yellow}UID file already exists for $model_name...${reset}"
					confirmation="${yellow}Model ID from file:${reset} $uid"
				fi

				uid=$uid
				model_name=$model_export_name_clean

				# Verify exported file size and display message accordingly (Free account model upload limit: 50MB)

				model_size=$(ls -s --block-size=MB "$current_file_blend" | awk '{print $1}')

				model_size_threshold="50"
				model_size_number="${model_size%MB}"

				if [[ "$model_size_number" -le "$model_size_threshold" ]]
				then
					model_size_message="${green}Model file size is below ${model_size_threshold}MB [ $model_size ]- File size threshold not exceeded.${reset}"
					color=$(tput setaf 2) # green

				elif [[ "$model_size_number" -gt "$model_size_threshold" ]]
				then
					model_size_message="${red}Warning: Model file size is above ${model_size_threshold}MB [ $model_size ] - Model cannot be uploaded to free subscription account due to maximum size limitation.${reset}"
					color=$(tput setaf 1) # red
				fi

				echo "$uid" > "$current_directory/uid"

				echo "${message}"
				echo "${confirmation}"
				echo ""
				echo "Model ID.....: $uid"
				echo "Model name...: $model_name"
				echo "${color}Model size...:${reset} $model_size"
				echo ""
				echo "${model_size_message}"
				echo ""
			else
				: #pass
			fi

		done < "$uid_list"

		echo "${cyan}Done.${reset}"
		echo ""
	done
done
